//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppEmployee.Extensions.Test.Quanlythuhocphi.Quanlythuhocphi.Quanlythuhocphi.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUTHU
    {
        public string SOPHIEU { get; set; }
        public string MaNV { get; set; }
        public string MaSV { get; set; }
        public Nullable<int> HocPhi { get; set; }
        public Nullable<int> MienGiam { get; set; }
        public Nullable<int> ThucThu { get; set; }
        public Nullable<System.DateTime> NgayThu { get; set; }
        public Nullable<int> MaLyDoThu { get; set; }
    
        public virtual LYDOTHU LYDOTHU { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual SINHVIEN SINHVIEN { get; set; }
    }
}
